### ISSUE TITLE
Example on PCM data

### ISSUE THREAD

**Issue by onthegit** [chcunningham/wc-talk#8]
Hello, thank you for the examples regarding the webcodecs apis. 

I am trying to construct AudioData object from raw PCM data (retrieved from wav file). I have the following (parsed from the header of the WAV file):
```
audioFormat: 1
bitsPerSample: 16
blockAlign: 4
byteRate: 176400
cbSize: 0
chunkId: "fmt "
chunkSize: 16
dwChannelMask: 0
headBitRate: 0
headEmphasis: 0
headFlags: 0
headLayer: 0
headMode: 0
headModeExt: 0
numChannels: 2
ptsHigh: 0
ptsLow: 0
sampleRate: 44100
```
And the actual Linear PCM data in ArrayBuffer.

How to construct the AudioData object from the ArrayBuffer so that it can be passed for encoding to "opus" codec.

```javascript
 const chunk = new AudioData({
          data: data,
          timestamp: 0,
          format: 'f32',//not sure what the format is
          numberOfChannels: 2,
          numberOfFrames: 1024,//again this number is arbitrary, do not know what to put here
          sampleRate: 44100,
        })
```
How to construct the rest of the ArrayBuffer into AudioData? The ```data.byteLength = 10406468``` 

AudioEncoder config:
```javascript
   {
      codec: 'opus',
      numberOfChannels: 2,
      sampleRate: 44100
    }
```

Thanks.

**Comment by guest271314** [comment]
You can create `AudioData` instances having 441 length, create an `Int8Array()` then `Int16Array()` from the buffer, parse to planar (2 channels), set `format` to `f32-planar`, something like 

```
let channelData = [];
// ...
let i = 0;
for (; i < value.buffer.byteLength; i++, this.readOffset++) {
  if (channelData.length === 441 * 4) {
    this.inputController.enqueue([...channelData]);
    channelData.length = 0;
   }
channelData.push(value[i]);
// ...
const int8 = new Int8Array(441 * 4);
const { value, done } = await this.inputReader.read();
  if (!done) {
    int8.set(new Int8Array(value));
   } else {
     console.log({done});
     return this.audioWriter.closed;
   }
   const int16 = new Int16Array(int8.buffer);
    // https://stackoverflow.com/a/35248852
    const channels = [
      new Float32Array(441),
      new Float32Array(441),
    ];
    for (let i = 0, j = 0, n = 1; i < int16.length; i++) {
      const int = int16[i];
      // If the high bit is on, then it is a negative number, and actually counts backwards.
     const float =
     int >= 0x8000
     ? -(0x10000 - int) / 0x8000
     : int / 0x7fff;
      // deinterleave
      channels[(n = ++n % 2)][!n ? j++ : j - 1] = float;
}
// ...
const data = new Float32Array(882);
data.set(left, 0);
data.set(right, 441);
const frame = new AudioData({
  timestamp,
  data,
  sampleRate: 44100,
  format: 'f32-planar',
  numberOfChannels: 2,
  numberOfFrames: 441,
});
```

See https://github.com/guest271314/captureSystemAudio/blob/4a7bbf8659808fbc01f3ccd14e4c0bbf520253d9/native_messaging/capture_system_audio/background.js#L148-L310, which captures raw PCM of audio output to speakers or headphones ("What-U-Hear"), microphone, or specific devices, e.g., `speech-dispatcher-espeak-ng` to capture and record speech synthesis output to a `MediaStreamTrack`, which can further encodemed/compressed or streamed with WebRTC, etc.

To get `timestamp` I create a stream of silence then pass that stream to `MediaStreamTrackProcessor` solely to generate `timestamp`.

Technically since Chromium implementation is always `53500` for first `opus` chunk and `60000` for remainder we could begin `timestamp` at `0`, set first to `53500`, and remainder to previous `timestamp` plus `60000`. The algorithm should achieve expected results using `60000` alone, though for accuracy the first chunk, from my tests, is `53500` `timestamp`.

FWIW Here I encode WebCodecs `'opus'` to a single file, and decode to WAV or playback with Media Source Extsensions. From tests so far the encoded file is less than Opus in WebM container for the same duration of media, 1 or 2 channels https://github.com/guest271314/WebCodecsOpusRecorder.

**Comment by guest271314** [comment]
An example of resampling 44100, 2 channel WAV input to 48000 sample rate `Float32Array`s using `AudioContext` (see https://github.com/w3c/webcodecs/issues/378), encoding to WebCodecs `'opus'`, playing back `EncodedAudioChunk`'s with Media Source Extensions.

```
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <input type="file" />
    <script>
      document.querySelector('input[type=file]').onchange = async (e) => {
        const wav = await e.target.files[0].arrayBuffer();
        const ac = new AudioContext({
          sampleRate: 48000,
        });
        let timestamp = 0,
          array = [],
          chunks = [],
          config = {
            numberOfChannels: 2,
            sampleRate: 48000,
            codec: 'opus',
          };
        const ab = await ac.decodeAudioData(wav);
        const left = ab.getChannelData(0);
        const right = ab.getChannelData(1);
        console.log(left, right);
        for (let i = 0; i < left.length; i += 480) {
          const data = new Float32Array(480 * 2);
          data.set(left.subarray(i, i + 480), 0);
          data.set(right.subarray(i, i + 480), 480);
          const frame = new AudioData({
            timestamp,
            data,
            sampleRate: 48000,
            format: 'f32-planar',
            numberOfChannels: 2,
            numberOfFrames: 480,
          });
          timestamp += frame.duration;
          array.push(frame);
        }
        console.log(array);
        const encoder = new AudioEncoder({
          error(e) {
            console.log(e);
          },
          output: async (chunk, metadata) => {
            if (metadata.decoderConfig) {
              config.description = metadata.decoderConfig.description;
            }
            chunks.push(chunk);
          },
        });
        console.log(await AudioEncoder.isConfigSupported(config));
        encoder.configure(config);
        for (const audioData of array) {
          encoder.encode(audioData);
        }
        await encoder.flush();
        console.log(chunks);
        const audio = new Audio();
        audio.controls = true;
        const events = [
          'loadedmetadata',
          'loadeddata',
          'canplay',
          'canplaythrough',
          'play',
          'playing',
          'pause',
          'waiting',
          'progress',
          'seeking',
          'seeked',
          'ended',
          'stalled',
          'timeupdate',
        ];
        for (const event of events) {
          audio.addEventListener(event, async (e) => {
            if (e.type === 'ended') {
            }
            if (e.type === 'loadedmetadata') {
              console.log(e.type);
              await audio.play();
            }
          });
        }
        document.body.appendChild(audio);

        const ms = new MediaSource();
        ms.addEventListener('sourceopen', async (e) => {
          console.log(e.type, config);
          URL.revokeObjectURL(audio.src);
          const sourceBuffer = ms.addSourceBuffer({
            audioConfig: config,
          });
          console.log(ms.activeSourceBuffers);
          sourceBuffer.onupdate = (e) => console.log(e.type);
          sourceBuffer.mode = 'sequence';
          for (const chunk of chunks) {
            await sourceBuffer.appendEncodedChunks(chunk);
          }
        });
        audio.src = URL.createObjectURL(ms);
      };
    </script>
  </body>
</html>
```

https://plnkr.co/edit/e2yskooQbI2gomFq?open=lib%2Fscript.js

**Comment by guest271314** [comment]
@onthegit FWIW WebCodecs 'opus' configuration and `EncodedAudioChunk`s encoded in a single file, decoded to WAV and/or Media Source Extsensions for playback. From tests the encoded file is less than Opus in WebM container produced by Chromium implementation of `MediaRecorder` for the same duration of media (1 or 2 channels) https://github.com/guest271314/WebCodecsOpusRecorder.

**Comment by onthegit** [comment]
@guest271314 thanks. So you are saying that I need to resample the 44100 to 48000?

**Comment by guest271314** [comment]
That would make the process simpler. Read the Web Audio API links in the WebCodecs issue.

**Comment by guest271314** [comment]
That would make the process simpler. Read the Web Audio API linked issues in the WebCodecs issue.

**Comment by guest271314** [comment]
@onthegit What are you trying to do with the `AudioData` objects?

**Comment by onthegit** [comment]
@guest271314  thanks for the replies. I will be encoding the AudioData to opus codec with webcodecs AudioEncoder. 

I managed to get this working so I am closing the issue, but if someone wants to add to discussion, can reply to this thread.

**Comment by guest271314** [comment]
> After doing more research on encoding, I managed to get this working so I am closing the issue, but if someone wants to add to the discussion or ask question, can reply to this thread.

How did you do that?

> There is no need of resampling, as the opus AudioEncoder buffers the audio data until 60000 duration is reached and resamples the data to 48000 cause that is the output of the AudioEncoder for opus codec.

I don't think that is the case as to buffering. 

What specific configuration did you use to encode with 44100, 2 channel sample rate, and how did you test playback?

**Comment by guest271314** [comment]
> There is no need of resampling, as the opus AudioEncoder buffers the audio data until 60000 duration is reached

I don't think that is the case. 

I was able to get 44100 sample rate,  2 channel `AudioData` to play as `EncodedAudioChunk` only when the original `AudioData` `duration` is `60000`. When `duration` is `10000` the playback is clipped.

**Comment by guest271314** [comment]
```
{
      codec: 'opus',
      numberOfChannels: 2,
      sampleRate: 44100
    }
```

Note, when `AudioEncoder` configuration is set to 44100, with `AudioData` input `duration` set to `60000` the first second of playback using Media Source Extensions is clipped; and 1 second is trimmmed from end of playback; reduced quality. From this Opus does not support 44100 sample rate https://github.com/xiph/opus/issues/43.
